name: Test on WSL
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - WSL - ${{ github.event_name }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
          - 'lts'
    steps:
      - uses: actions/checkout@v5
      - name: Setup WSL
        uses: Vampire/setup-wsl@v6
        with:
          distribution: Ubuntu-22.04
          additional-packages: curl xclip xvfb dbus-x11
      - name: Install Julia via juliaup
        shell: wsl-bash {0}
        run: |
          curl -fsSL https://install.julialang.org | sh -s -- --yes
          export PATH="$HOME/.juliaup/bin:$PATH"
          juliaup add ${{ matrix.version }}
          juliaup default ${{ matrix.version }}
          julia --version
      - name: Build package
        shell: wsl-bash {0}
        run: |
          export PATH="$HOME/.juliaup/bin:$PATH"
          julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.build()'
      - name: Run tests
        shell: wsl-bash {0}
        run: |
          export PATH="$HOME/.juliaup/bin:$PATH"
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 2
          julia --project=. -e 'using Pkg; Pkg.test(coverage=true)'
      - name: Process coverage
        shell: wsl-bash {0}
        run: |
          export PATH="$HOME/.juliaup/bin:$PATH"
          julia --project=. -e 'using Pkg; Pkg.add("Coverage"); using Coverage; LCOV.writefile("lcov.info", Codecov.process_folder())'
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
